# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/saranthyr/Unreal_Engine_5.6.1

TARGETS = \
	EagleEye-Android-DebugGame  \
	EagleEye-Android-Development  \
	EagleEye-Android-Shipping  \
	EagleEye-Linux-DebugGame  \
	EagleEye-Linux-Development  \
	EagleEye-Linux-Shipping  \
	EagleEye-LinuxArm64-DebugGame  \
	EagleEye-LinuxArm64-Development  \
	EagleEye-LinuxArm64-Shipping  \
	EagleEye \
	EagleEyeEditor-Linux-DebugGame  \
	EagleEyeEditor-Linux-Development  \
	EagleEyeEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend EagleEyeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug EagleEyeEditor-Linux-Debug


EagleEye-Android-DebugGame:
	 $(BUILD) EagleEye Android DebugGame  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-Android-Development:
	 $(BUILD) EagleEye Android Development  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-Android-Shipping:
	 $(BUILD) EagleEye Android Shipping  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-Linux-DebugGame:
	 $(BUILD) EagleEye Linux DebugGame  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-Linux-Development:
	 $(BUILD) EagleEye Linux Development  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-Linux-Shipping:
	 $(BUILD) EagleEye Linux Shipping  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-LinuxArm64-DebugGame:
	 $(BUILD) EagleEye LinuxArm64 DebugGame  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-LinuxArm64-Development:
	 $(BUILD) EagleEye LinuxArm64 Development  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye-LinuxArm64-Shipping:
	 $(BUILD) EagleEye LinuxArm64 Shipping  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEye: EagleEye-Linux-Development

EagleEyeEditor-Linux-DebugGame:
	 $(BUILD) EagleEyeEditor Linux DebugGame  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEyeEditor-Linux-Development:
	 $(BUILD) EagleEyeEditor Linux Development  -Project="/home/saranthyr/EagleEye/EagleEye.uproject" $(ARGS)

EagleEyeEditor: EagleEyeEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/saranthyr/EagleEye/EagleEye.uproject" -Game 

.PHONY: $(TARGETS)
