#!/usr/bin/env bash
set -euo pipefail

UE_TRUE_SCRIPT_NAME="$(readlink -f "$0")"
UE_PROJECT_ROOT="$(dirname "$UE_TRUE_SCRIPT_NAME")"
PACKAGE_ROOT="$UE_PROJECT_ROOT/EagleEye"

export ORT_MIGRAPHX_CACHE_PATH="${ORT_MIGRAPHX_CACHE_PATH:-$PACKAGE_ROOT/Saved/MIGraphXCache/data}"
export ORT_MIGRAPHX_MODEL_CACHE_PATH="${ORT_MIGRAPHX_MODEL_CACHE_PATH:-$PACKAGE_ROOT/Saved/MIGraphXCache/models}"
export ORT_MIGRAPHX_EXHAUSTIVE_TUNE="${ORT_MIGRAPHX_EXHAUSTIVE_TUNE:-0}"

mkdir -p "$ORT_MIGRAPHX_CACHE_PATH" "$ORT_MIGRAPHX_MODEL_CACHE_PATH"
chmod +x "$PACKAGE_ROOT/Binaries/Linux/EagleEye"
exec "$PACKAGE_ROOT/Binaries/Linux/EagleEye" EagleEye "$@"
