;METADATA=(Diff=true, UseCommands=true)

[/Script/EagleEye.EagleEyeDetectionSettings]
InferenceBackend=Auto
OnnxRuntimeExecutionProvider=DirectML
ModelPathOverride=yolo26l.onnx
NamesPathOverride=coco.names
DarknetCfgPathOverride=yolov7.cfg
bOpenCVDNNPreferCUDA=True
bOpenCVDNNUseFP16=True
OnnxInputSize=640
bUseLetterbox=True
LetterboxValue=114
ConfidenceThreshold=0.250000
NmsThreshold=0.450000
MaxActiveSharedDetectionBots=3
SharedDetectionMaxBotDistance=8000.000000
bRecordFrameTimes=True
FrameTimeCsvPath=
bResetFrameTimeLogOnBeginPlay=True
FrameTimeFlushInterval=60
bEnablePathfindingDecisionLogs=True
bEnablePathfindingObjectLogs=True
bEnableDetectionDebugLogs=True
bEnableDetectionPerformanceLogs=True
bEnableDetectionMetricLogs=True

