;METADATA=(Diff=true, UseCommands=true)

[/Script/EagleEye.EagleEyeDetectionSettings]
InferenceBackend=ONNXRuntime
OnnxRuntimeExecutionProvider=CPU
ModelPathOverride=yolo26l
NamesPathOverride=coco.names
bOpenCVDNNPreferCUDA=True
bOpenCVDNNUseFP16=True
OnnxInputSize=640
bUseLetterbox=True
LetterboxValue=114
ConfidenceThreshold=0.750000
NmsThreshold=0.550000
bPreloadModelHostOnBeginPlay=True
MaxActiveModelUsers=5
MaxQueuedModelFrames=2
FrameSourceFPS=10.000000
FrameSourceWidth=640
FrameSourceHeight=640
MaxModelUserDistanceToPlayer=3000.000000
bStaggerInitialFrameSourceCapture=True
MaxInitialFrameSourceCaptureDelay=0.750000
bRecordFrameTimes=True
FrameTimeCsvPath=
bResetFrameTimeLogOnBeginPlay=True
FrameTimeFlushInterval=60
bEnablePathfindingDecisionLogs=True
bEnablePathfindingObjectLogs=True
bEnableDetectionDebugLogs=True
bEnableDetectionPerformanceLogs=True
bEnableDetectionMetricLogs=True

